require: rubocop-rspec
AllCops:
  Exclude:
    - db/schema.rb
    - node_modules/**/*
    - web/**/*
    - bin/*

Documentation:
  Enabled: false

Metrics/AbcSize:
  Max: 40

Metrics/LineLength:
  Max: 120
  Exclude:
    - db/**/*.rb
    - spec/**/*.rb

Metrics/MethodLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Naming/UncommunicativeMethodParamName:
  # Allow parameters to be named '_' if they are not used
  AllowedNames:
    - _
    - id

Rails/HasAndBelongsToMany:
  Enabled: False

RSpec/NestedGroups:
  Max: 4

Style/HashSyntax:
  EnforcedStyle: hash_rockets

Style/NestedParenthesizedCalls:
  Enabled: false

Style/BlockDelimiters:
  Exclude:
    - config/routes.rb

Style/SafeNavigation:
  Enabled: false
