language: ruby
cache:
  bundler: true
rvm:
  - 2.5.0
before_script:
  - (git submodule init && git submodule update)
  - mkdir data
  - mkdir -p tmp/uploads
  - bundle exec rails db:create
  - bundle exec rails db:migrate
script:
  - bundle exec rspec
notifications:
  slack:
    secure: n2fCeQht38gFw+qT4OXbjTdbPyPNjqYBXHEzt4mBMhNacTSm2gwyKEXV5RCwRfeXAKUPTVWZwQ82rd8HAoQ1DiYtCxKD4iUOBS6uGOo4f8RKa4xxuuMrA/hPpEQUXTvvYaL6gOYs9p2F4tugrHbd7ys/8KgGK/zu8DZBQcqkyOJMsHfwWhIrmoGZu6J5xPIOeHhaSrhBb6cMnAeIDEO1RzMsp2Fzh9qOf1a/FPWceXrY3v0yzJmUqxGaqKFqZx52/jjTF5PNblZJrxzH+uIhJBMqx17+x7o7RzQSAuaaMAoilGT+DfL1MDIrbBzzEHLx7AtcoEQOvxTihUWWyZLwToKpcGey7kGBgrIPKo/bxd2rB9mB34Nxn5AVGyDIhM8+XPHCmKkNZcYjXxVc5mEAOMMu541+D7i4oNIIZq+Mnom+aqXR5kd++6BcGLEkHRrSP50pqrnib/w64NbE4CTrd/RKnPRfM/M3Bi2fMx6Ns4LotsI5iQNYdbBEt55wC426YBqoVywwEsp5bx+FBZtN/RuBQKPMaV+qG5hIqA3cOLDs7bNYIazEJwht5ssas9aKdmlxiqJLjMM1ckjhZ5mre4NBO1PFBoxMEv8xASiyJbvP92lHwPJUbvDbnvJo5RM59mWxX+zdx0ypdnJomulSRo09b9YXslQX7jgryX4CXRY=
